language: node_js
node_js:
  - '8'

sudo: false
cache:
  directories:
    - 'node_modules'

install:
  - yarn

script:
  - cd packages/workerdb && yarn link
  - cd packages/react-workerdb && yarn link workerdb
  - yarn build
  - yarn test
  - yarn coverage
