language: node_js
node_js:
  - '8'

sudo: false

cache: yarn

install:
  - yarn
  - cd $TRAVIS_BUILD_DIR/packages/workerdb && yarn link
  - cd $TRAVIS_BUILD_DIR/packages/react-workerdb && yarn link workerdb

script:
  - yarn build
  - yarn test
  - yarn coverage
