language: node_js
node_js:
  - '8'

sudo: false
cache:
  directories:
    - 'node_modules'

install:
  - yarn
  - yarn global add codecov

script:
  - yarn bootstrap
  - yarn build
  - yarn test
  - yarn codecov
